apiVersion: apps/v1
kind: Deployment
metadata:
  name: appserver-Deployment
spec:
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      labels:
        app: appserver
    spec:
      containers:
      - name: appserver
        image: appserver:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
